services:
  backend:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    env_file: .env.prod
    depends_on:
      - postgres
      - minio
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: docdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
volumes:
  pg_data:
  minio_data:
